sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t 411994/docker-react Dockerfile.dev .

script:
  - docker run -e CI=true 411994/docker-react npm run test
