version: '3'
services: 
  react-app:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/reactApp
      - /reactApp/node_modules
    ports: 
      - "3000:3000"